-----TRIGERSSSS
USE MONETIX_APP;
GO
--------------------------------------------------------------------------
CREATE  TRIGGER DELETE_TRANSACTION_LOGIC
ON TRANSACTIONS
INSTEAD OF DELETE
AS
BEGIN
	UPDATE TRANSACTIONS
	SET IS_ACTIVE = 0
	WHERE TRANSACTIONID IN (SELECT TRANSACTIONID FROM deleted);
END;

GO
-------------------------------------------------
---VIEWS
---SUMMARY OF EXPENSES OR INCOME FOR CATEGORY ANS USER
CREATE VIEW VW_SUMMARY_OF_TRANSACTIONS AS
SELECT
    U.ID_USER,
    U.NAME_USER + ' ' + U.LAST_NAME AS FULL_NAME,
    C.NAME_CATEGORY,
    SUM(T.AMOUNT) AS TOTAL_AMOUNT,
    COUNT(T.TRANSACTIONID) AS TRANSACTION_COUNT
FROM 
    TRANSACTIONS T
JOIN USERS U ON T.USERID = U.ID_USER
JOIN CATEGORIES C ON T.CATEGORYID = C.CATEGORY_ID
GROUP BY 
    U.ID_USER, U.NAME_USER, U.LAST_NAME, C.NAME_CATEGORY;

GO
	SELECT * FROM VW_SUMMARY_OF_TRANSACTIONS;

	SELECT * 
FROM VW_SUMMARY_OF_TRANSACTIONS
WHERE TOTAL_AMOUNT < 324.22
ORDER BY TOTAL_AMOUNT DESC;